python ./examples_original/run_glue.py \
    --model_type bert \
    --model_name_or_path pretrained_bert \
    --task_name roc \
    --do_train \
    --do_lower_case \
    --data_dir glue_data_new/roc \
    --max_seq_length 35 \
    --per_gpu_eval_batch_size=1   \
    --per_gpu_train_batch_size=4   \
    --gradient_accumulation_steps 1 \
    --learning_rate 2e-5 \
    --eval_all_checkpoints \
    --evaluate_during_training \
    --num_train_epochs 2.0 \
    --logging_steps 4000 \
    --save_steps 0 \
    --cuda_ip cuda:0 \
    --overwrite_output_dir \
    --ff_size 3072 \
    --heads 8 \
    --para_dropout 0.1 \
    --inter_layers 2 \
    --beam_size 16 \
    --pairwise_loss_lam 0.6 \
    --output_dir output/roc_batch4_lr2_2epo_loss06/
